import SidebarCart from "@/components/SidebarCart";
import SidebarMenu from "@/components/SidebarMenu";

export const metadata = {
  title: "POS Coffee",
  description: "Generated by POS Coffee",
};

export default function OrderLayout({ children }) {
  return (
    <div className="flex">
      <SidebarMenu />

      <div className="flex-1 bg-gray-100 min-h-screen ml-72 mr-96">
        {children}
      </div>

      <SidebarCart />
    </div>
  );
}
