import "./globals.css";

export const metadata = {
  title: "POS Coffee",
  description: "Generated by POS Coffee",
};

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
